giantswarm:
    fluxOperator:
        verticalPodAutoscaler:
            enabled: true
            force: false

fluxOperator:
    enabled: true

    image:
        repository: gsoci.azurecr.io/giantswarm/flux-operator

    priorityClassName: "system-cluster-critical"

    serviceMonitor:
        create: true
