name: Auto upgrade the Helm Chart

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch: {}

jobs:
  run_upgrade:
    name: Run the upgrade script
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.0
      - run: ./hack/auto-upgrade.sh
